### ISSUE TITLE
Connection failed - How to fix?

### ISSUE THREAD

**Issue by invisibley** [Baterka/CSGOHunt.com-Copy#1]
Site says connection failed and also browser console says Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://vaioajfgafjadiofg.com................. (Reason: CORS request did not succeed).

**Comment by Baterka** [comment]
There is many things what can cause this. This project is long time unmaintained an I am not giving free support for it. Sorry.
